[project]
name = "sufecoursehelper"
version = "1.0.0"
description = "SUFE Course Helper"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["bs4>=0.0.2", "lxml>=5.4.0", "requests>=2.32.4"]
